name: Run Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0/30 11-23 * * MON-FRI"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Retrieve keeper secrets
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            QODeOw-dwElfR5kzunCvwg/field/login > env:MULESOFT_USERNAME
            QODeOw-dwElfR5kzunCvwg/field/password > env:MULESOFT_PASS
            ct0MNUfbMRs3dXCDJpjJUA/custom_field/app_id > env:GH_APP_ID
            ct0MNUfbMRs3dXCDJpjJUA/field/keyPair[0][privateKey] > env:GH_APP_PRIVATE_KEY
            9Vi7qUgp2ht2JvmZRs-YXA/field/login > env:AWS_ACCESS_KEY_ID
            9Vi7qUgp2ht2JvmZRs-YXA/field/password > env:AWS_SECRET_ACCESS_KEY
      - name: Generate a github token
        id: generate-gh-app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          app-id: ${{ env.GH_APP_ID }}
          private-key: ${{ env.GH_APP_PRIVATE_KEY }}
          owner: CityOfPhiladelphia
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f7fad228a053c69a98e24f8e4f6cf40db8f61e08 # v44.2.1
        with:
          token: ${{ steps.generate-gh-app-token.outputs.token }}
          configurationFile: config.js
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|AWS_REGION|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY)$"
        # See https://github.com/renovatebot/github-action?tab=readme-ov-file#environment-variables
        env:
          RENOVATE_MULESOFT_USERNAME: ${{ env.MULESOFT_USERNAME }}
          RENOVATE_MULESOFT_PASS: ${{ env.MULESOFT_PASS }}
          # LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
