name: Run Renovate
on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Retrieve keeper secrets
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |-
            QODeOw-dwElfR5kzunCvwg/field/login > env:MULESOFT_USERNAME
            QODeOw-dwElfR5kzunCvwg/field/password > env:MULESOFT_PASS
            ct0MNUfbMRs3dXCDJpjJUA/custom_field/app_id > env:GH_APP_ID
            ct0MNUfbMRs3dXCDJpjJUA/field/keyPair[0][privateKey] > env:GH_APP_PRIVATE_KEY
      - name: Generate a github token
        id: generate-gh-app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.GH_APP_ID }}
          private-key: ${{ env.GH_APP_PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.19
        with:
          token: ${{ steps.generate-gh-app-token.outputs.token }}
          configurationFile: config.js
        # See https://github.com/renovatebot/github-action?tab=readme-ov-file#environment-variables
        env:
          RENOVATE_MULESOFT_USERNAME: ${{ env.MULESOFT_USERNAME }}
          RENOVATE_MULESOFT_PASS: ${{ env.MULESOFT_PASS }}
          RENOVATE_PLATFORM: github
